# Config to test registry models that were not exercised in the last run
# Run location: c:\dev\silky\api_cost_multiplier
input_folder: C:\dev\silky\api_cost_multiplier\test\mdinputs
output_folder: C:\dev\silky\api_cost_multiplier\test\mdoutputs_untested
instructions_file: C:\dev\silky\api_cost_multiplier\test\instructions.txt
one_file_only: true
iterations_default: 1
max_sections: 1

# Runs: GPTR-style runs for each untested model (one run each)
runs:
- type: gptr
  provider: openai
  model: codex-mini
- type: gptr
  provider: openai
  model: o3-pro
- type: gptr
  provider: openai
  model: o1
- type: gptr
  provider: openai
  model: o1-preview
- type: gptr
  provider: google_genai
  model: gemini-live-2.5-flash-preview
- type: gptr
  provider: anthropic
  model: claude-opus-4-1-20250805
- type: gptr
  provider: anthropic
  model: claude-opus-4-20250514-thinking
- type: gptr
  provider: anthropic
  model: claude-3-7-sonnet-20250219
- type: gptr
  provider: anthropic
  model: claude-3-7-sonnet-latest
- type: gptr
  provider: anthropic
  model: claude-3-5-haiku-20241022
- type: gptr
  provider: anthropic
  model: claude-3-5-haiku-latest
- type: gptr
  provider: openrouter
  model: default
