# doc_eval/config.yaml
llm_api:

  max_concurrent_llm_calls: 2 # Reduced for testing

single_doc_eval:
  trial_count: 1 # Reduced for testing
  criteria_file: criteria.yaml

pairwise_eval:
  trial_count: 1 # Reduced for testing
  criteria_file: criteria.yaml

models:
  model_a:
    name: gpt-4.1-nano
    provider: openai
  model_b:
    name: gpt-4.1-nano
    provider: openai
